// Generated by CoffeeScript 1.8.0
(function() {
  $('.js-options input').change(function() {
    var check, type;
    type = $(this).attr('type');
    check = $(this).parent('label');
    if (type === 'checkbox') {
      return check.toggleClass('checked');
    } else if (type === 'radio') {
      check.siblings('label').removeClass('checked');
      return check.addClass('checked');
    }
  });

}).call(this);

// Generated by CoffeeScript 1.8.0
(function() {
  $('.js-scroll').click(function(e) {
    var dest;
    dest = $(this).attr('href');
    e.preventDefault();
    return $('html, body').animate({
      scrollTop: $(dest).offset().top
    }, 1000);
  });

}).call(this);

// Generated by CoffeeScript 1.8.0
(function() {
  $('.tabs').each(function() {
    var $active, $content, $links;
    $links = $(this).find('a');
    $active = $($links.filter('[href=\'' + location.hash + '\']')[0] || $links[0]);
    $active.addClass('active');
    $content = $($active.attr('href'));
    $links.not($active).each(function() {
      return $($(this).attr('href')).hide();
    });
    return $(this).on('click', 'a', function(e) {
      $active.removeClass('active');
      $content.hide();
      $active = $(this);
      $content = $($(this).attr('href'));
      $active.addClass('active');
      $content.show();
      return e.preventDefault();
    });
  });

}).call(this);

// Generated by CoffeeScript 1.8.0
(function() {
  $('.js-open-canvas').click(function(e) {
    var target, targetName;
    target = $(this).find('a').attr('href');
    targetName = target.substring(4);
    $(this).toggleClass('active');
    $(target).toggleClass('offcanvas--open');
    if ($(target).hasClass('offcanvas--left')) {
      $('.offcanvas--push').toggleClass('offcanvas--push-left');
      $('.offcanvas--squish').toggleClass('offcanvas--squish-left');
    } else if ($(target).hasClass('offcanvas--right')) {
      $('.offcanvas--push').toggleClass('offcanvas--push-right');
      $('.offcanvas--squish').toggleClass('offcanvas--squish-right');
    }
    return e.preventDefault();
  });

}).call(this);
