// Generated by CoffeeScript 1.8.0
(function() {


}).call(this);

// Generated by CoffeeScript 1.8.0
(function() {
  $('.content > iframe').each(function() {
    var isMap, map, source;
    source = $(this).attr('src');
    map = /maps.google/;
    isMap = map.test(source);
    if (isMap) {
      return $(this).wrap('<figure class="map"></figure>');
    } else {
      return $(this).wrap('<figure class="video"></figure>');
    }
  });

  $('.video').fitVids();

}).call(this);

// Generated by CoffeeScript 1.8.0
(function() {
  $(document).on('click', '.js-reveal', function(e) {
    var target;
    target = $(this).attr('href');
    $(target).toggleClass('opened');
    return e.preventDefault();
  });

}).call(this);
